apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod

spec:
  containers:
  - name: mysql
    image: mysql:8.3
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: GmNgl69ZW9
    - name: MYSQL_DATABASE
      value: sql8774445