apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80          # service port inside cluster
      targetPort: 80    # container port
      nodePort: 30081   # external port on node
  type: NodePort
