apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend
        image: iotinsighthub/insight-hub-dashboard:s4-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
