# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: insight-hub
  labels:
    app: insight-hub
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 80            # Service port inside the cluster
      targetPort: 80      # Pod’s containerPort
      nodePort: 30080     # External port on each Node (must be 30000–32767)
  selector:
    app: insight-hub
    component: frontend
