apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: iotinsighthub/insight-hub-dashboard:s4-v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/runtime-config.json
              subPath: runtime-config.json
      volumes:
        - name: config-volume
          configMap:
            name: frontend-runtime-config
