apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: iotinsighthub/insight-hub-dashboard:s4-v1
        imagePullPolicy: Always # Sometimes you might push a new version of the image with the same tag, so you don't wanna use the cached unupdated image
        ports:
        - containerPort: 80
