# Start from the official MySQL 8.3 image
FROM mysql:8.3



# Optional: copy custom configuration or initialization SQL scripts
# COPY ./my.cnf /etc/mysql/my.cnf
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Expose the default MySQL port
EXPOSE 3306
