apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
data:
  runtime-config.json: |
    {
      "domain": "http://backend-route-hyper288-dev.apps.rm2.thpm.p1.openshiftapps.com",
      "port": "80"
    }
